/* Molgenis */
CREATE DATABASE molgenisdb;
CREATE USER molgenis WITH LOGIN NOSUPERUSER INHERIT CREATEROLE ENCRYPTED PASSWORD 'molgenis';
GRANT ALL PRIVILEGES ON DATABASE molgenisdb TO molgenis;

/* REMS */
CREATE DATABASE remsdb;
CREATE USER remsuser WITH LOGIN NOSUPERUSER INHERIT CREATEROLE ENCRYPTED PASSWORD 'remspass';
GRANT ALL PRIVILEGES ON DATABASE remsdb TO remsuser;


/* REMS */
CREATE DATABASE keycloakdb;
CREATE USER keycloakuser WITH LOGIN NOSUPERUSER INHERIT CREATEROLE ENCRYPTED PASSWORD 'keycloakpass';
GRANT ALL PRIVILEGES ON DATABASE keycloakdb TO keycloakuser;
